version: 0.0
os: linux
files: 
  - source: /
    destination: /home/ec2-user/app/scripts
hooks:
  BeforeInstall:
    - location: kickstart.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: pull_image.sh
      timeout: 300
      runas: root
  StartApplication:
    - location: start_container.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: validate.sh
      timeout: 300
      runas: root