version: 0.0
os: linux
files: 
  - source: /
    destination: /home/ec2-user/app
hooks:
  StopApplication:
    - location: deployment/scripts/stop_container.sh
      timeout: 300
      runas: root
  BeforeInstall: 
    - location: deployment/scripts/cleanup_instance.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: deployment/scripts/pull_image.sh
      timeout: 300
      runas: root
  StartApplication:
    - location: deployment/scripts/start_container.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: deployment/scripts/validate.sh
      timeout: 300
      runas: root