version: 0.0
os: linux
files: 
  - source: /scripts
    destination: /home/ec2-user/app/
hooks:
  ApplicationStop:
    - location: stop_container.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: kickstart.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: pull_image.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: start_container.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: validate.sh
      timeout: 300
      runas: root