version: 0.2

env: 
  docker_image: simple-api
  docker_registry_urlL: toshiiiiiiii/prepo_shi
  docker_email: toshi.olangar04@gmail.com
  secrets-manager:
    docker_password: "docker-password"

phases:
  install:
    commands:
      - echo Entered install phase
      - apt-get update -y
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt
  build:
    commands:
      - echo Build started `date`
      - echo "$docker_password" | docker login -u "$docker_email" --password-stdin    
      - docker build -t "$docker_image_NAME:latest" .
      - docker tag "$docker_image_NAME":latest "$docker_registry_urlL":latest
      - docker push "$docker_registry_urlL":latest