version: 0.2

env: 
  variables:
    ecr_repo: 167295297769.dkr.ecr.us-east-2.amazonaws.com/testspace/aws-devops

phases:
  install:
    commands:
      - echo Entered install phase
      - apt-get update -y
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo Entered test phase, cloning the code
      - git config --global credential.helper '!aws codecommit credential-helper $@'
      - git config --global credential.UseHttpPath true
      - git clone https://git-codecommit.us-east-2.amazonaws.com/v1/repos/my-app      
      - cd my-app
      - pylint app.py
      - pytest --cov=app --cov-report=html
  build:
    commands:
      - echo Entered pre_build phase
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 167295297769.dkr.ecr.us-east-2.amazonaws.com
      - docker build -t aws-devops .
      - docker tag aws-devops:latest 167295297769.dkr.ecr.us-east-2.amazonaws.com/testspace/aws-devops:latest